name: My Test Workflow  
on: 
  workflow_dispatch:
  push:
    branches:
      -master

jobs:
  testing:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-20.6.1-chrome-116.0.5845.187-1-ff-117.0-edge-116.0.1938.76-1.
    steps:
      - name: Get the project code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install --force  
      - name: Run tests
        run: npm run cypress:e2e
