name: Ny Test Workflow
om: workflow_dispatch 

jobs: 
  testing:
    runs-on: ubuntu-latest 
    steps:
        - name: Get the project code 
          users: actions/checkout@v4 
        - name: Install dependencies
          run: npm install --force
          - name: Run tests
            run: npm run cypress:e2e